name: kimsufi monitor

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "*/5 * * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: 启用 Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry update

      - name: 北美 KS-10 监控
        run: |
          poetry run python kimsufi.py --hardware 1804sk21

      - name: 欧洲 KS-10 监控
        run: |
          poetry run python kimsufi.py --hardware 1801sk21
